routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(['middleware' => ['guest']], function () {

    Route::get('/','Auth\LoginController@showLoginForm');
    Route::post('/login', 'Auth\LoginController@login')->name('login');

});


Route::group(['middleware' => ['auth']], function () {

    Route::post('/logout', 'Auth\LoginController@logout')->name('logout');

    Route::get('/home', 'HomeController@index');


    Route::group(['middleware' => ['Comprador']], function () {

        Route::resource('categoria', 'CategoriaController');
        Route::resource('producto', 'ProductoController');
        Route::get('/listarProductoPdf', 'ProductoController@listarPdf')->name('productos_pdf');
        Route::resource('proveedor', 'ProveedorController');
        Route::resource('compra', 'CompraController');
        Route::get('/pdfCompra/{id}', 'CompraController@pdf')->name('compra_pdf');

    });

    Route::group(['middleware' => ['Vendedor']], function () {

         Route::resource('categoria', 'CategoriaController');
         Route::resource('producto', 'ProductoController');
         Route::get('/listarProductoPdf', 'ProductoController@listarPdf')->name('productos_pdf');
         Route::resource('cliente', 'ClienteController');
         Route::resource('venta', 'VentaController');
         Route::get('/pdfVenta/{id}', 'VentaController@pdf')->name('venta_pdf');
         Route::resource('credito', 'CreditoController');

    });

    Route::group(['middleware' => ['Administrador']], function () {

      Route::resource('categoria', 'CategoriaController');
      Route::resource('producto', 'ProductoController');
      Route::get('/listarProductoPdf', 'ProductoController@listarPdf')->name('productos_pdf');
      Route::resource('proveedor', 'ProveedorController');
      Route::resource('compra', 'CompraController');
      Route::get('/pdfCompra/{id}', 'CompraController@pdf')->name('compra_pdf');
      Route::resource('venta', 'VentaController');
      Route::get('/pdfVenta/{id}', 'VentaController@pdf')->name('venta_pdf');
      Route::resource('cliente', 'ClienteController');
      Route::resource('rol', 'RolController');
      Route::resource('user', 'UserController');
      Route::resource('credito', 'CreditoController');
      Route::resource('transferencia', 'TransferenciaController');
      Route::get('/listarVentaPdf', 'VentaController@listarMesesPdf')->name('ventas_Meses_pdf');
      Route::get('/listarCreditoPdf', 'CreditoController@listarMesesPdf')->name('creditos_Meses_pdf');



    });


});

app/Credito.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Credito extends Model
{
    protected $table = 'creditos';
    protected $fillable =[
        'idcliente', 
        'idusuario',
        'tipo_identificacion',
        'num_venta',
        'fecha_venta',
        'impuesto',
        'total',
        'estado'
    ];
}

app/Http/Controllers/CreditoController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Credito;
use App\DetalleCredito;
use Illuminate\Support\Facades\Redirect;
use Carbon\Carbon;
use DB;

class CreditoController extends Controller
{

    public function index(Request $request){

        if($request){

           $sql=trim($request->get('buscarTexto'));
            $creditos=Credito::join('clientes','creditos.idcliente','=','clientes.id')
           ->join('users','creditos.idusuario','=','users.id')
            ->join('detalle_creditos','creditos.id','=','detalle_creditos.idcredito')
             ->select('creditos.id','creditos.tipo_identificacion',
             'creditos.num_venta','creditos.fecha_venta','creditos.impuesto',
             'creditos.estado','creditos.total','clientes.nombre as cliente','users.nombre')
            ->where('creditos.num_venta','LIKE','%'.$sql.'%')
            ->orderBy('creditos.id','desc')
            ->groupBy('creditos.id','creditos.tipo_identificacion',
            'creditos.num_venta','creditos.fecha_venta','creditos.impuesto',
            'creditos.estado','creditos.total','clientes.nombre','users.nombre')
            ->paginate(8);
/*
             $sql=trim($request->get('buscarTexto'));
            $creditos=Credito::join('clientes','creditos.idcliente','=','clientes.id')
            ->join('users','creditos.idusuario','=','users.id')
        ->select('creditos.id','creditos.tipo_identificacion',
             'creditos.num_venta','creditos.fecha_venta','creditos.impuesto',
             'creditos.estado','creditos.total','users.nombre')
            ->where('creditos.num_venta','LIKE','%'.$sql.'%')
            ->orderBy('creditos.id','desc')
            ->groupBy('creditos.id','creditos.tipo_identificacion',
            'creditos.num_venta','creditos.fecha_venta','creditos.impuesto',
            'creditos.estado','creditos.total','users.nombre')
            ->paginate(8);
            */

            return view('creditos.index',["creditos"=>$creditos,"buscarTexto"=>$sql]);
            //return $creditos;
        }


     }

        public function create(){

             /*listar las clientes en ventana modal*/
             $clientes=DB::table('clientes')->get();

             /*listar los productos en ventana modal*/
             $productos=DB::table('productos as prod')
             /*Omision por detalles*/
            /* ->join('detalle_compras','prod.id','=','detalle_compras.idproducto')*/
             ->select(DB::raw('CONCAT(prod.codigo," ",prod.nombre) AS producto'),'prod.id','prod.stock','prod.precio_venta')
             ->where('prod.condicion','=','1')
             /*->where('prod.stock','=','0')*/
            ->groupBy('producto','prod.id','prod.stock','prod.precio_venta')
             ->get();



             return view('creditos.create',["clientes"=>$clientes,"productos"=>$productos]);

        }

         public function store(Request $request){


             try{

                 DB::beginTransaction();
                 $mytime= Carbon::now('America/Mexico_city');

                 $credito = new Credito();
                 $credito->idcliente = $request->id_cliente;
                 $credito->idusuario = \Auth::user()->id;
                 $credito->tipo_identificacion = $request->tipo_identificacion;
                 $credito->num_venta = $request->num_venta;
                 $credito->fecha_venta = $mytime->toDateString();
                 $credito->impuesto = "0.20";
                 $credito->total=$request->total_pagar;
                 $credito->estado = 'Registrado';
                 $credito->save();

                 $id_producto=$request->id_producto;
                 $cantidad=$request->cantidad;
                 $descuento=$request->descuento;
                 $precio=$request->precio_venta;


                 //Recorro todos los elementos
                 $cont=0;

                  while($cont < count($id_producto)){

                     $detalle = new DetalleCredito();
                     /*enviamos valores a las propiedades del objeto detalle*/
                     /*al idcompra del objeto detalle le envio el id del objeto credito, que es el objeto que se ingresó en la tabla creditos de la bd*/
                     /*el id es del registro de la credito*/
                     $detalle->idcredito = $credito->id;
                     $detalle->idproducto = $id_producto[$cont];
                     $detalle->cantidad = $cantidad[$cont];
                     $detalle->precio = $precio[$cont];
                     $detalle->descuento = $descuento[$cont];
                     $detalle->save();
                     $cont=$cont+1;
                 }

                 DB::commit();

             } catch(Exception $e){

                 DB::rollBack();
             }

             return Redirect::to('credito');
         }



         public function show($id){

             //dd($id);
             //dd($request->all());

             /*mostrar credito*/

             //$id = $request->id;
              $credito = Credito::join('clientes','creditos.idcliente','=','clientes.id')
             ->join('detalle_creditos','creditos.id','=','detalle_creditos.idcredito')
             ->select('creditos.id','creditos.tipo_identificacion','creditos.idcliente',
             'creditos.num_venta','creditos.fecha_venta','creditos.impuesto',
             'creditos.estado','clientes.nombre',
             DB::raw('sum(detalle_creditos.cantidad*precio - detalle_creditos.cantidad*precio*descuento/100) as total')
             )
             ->where('creditos.id','=',$id)
             ->orderBy('creditos.id', 'desc')
             ->groupBy('creditos.id','creditos.tipo_identificacion',
             'creditos.num_venta','creditos.fecha_venta','creditos.impuesto',
             'creditos.estado','clientes.nombre','creditos.idcliente')
             ->first();
             /*
             $credito = Credito::join('detalle_creditos','creditos.id','=','detalle_creditos.idcredito')
             ->select('creditos.id','creditos.tipo_identificacion',
             'creditos.num_venta','creditos.fecha_venta','creditos.impuesto',
             'creditos.estado',
             DB::raw('sum(detalle_creditos.cantidad*precio - detalle_creditos.cantidad*precio*descuento/100) as total')
             )
             ->where('creditos.id','=',$id)
             ->orderBy('creditos.id', 'desc')
             ->groupBy('creditos.id','creditos.tipo_identificacion',
             'creditos.num_venta','creditos.fecha_venta','creditos.impuesto',
             'creditos.estado')
             ->first();
                     */
             /*mostrar detalles*/
             $detalles = DetalleCredito::join('productos','detalle_creditos.idproducto','=','productos.id')
             ->select('detalle_creditos.idproducto','detalle_creditos.cantidad','detalle_creditos.precio','detalle_creditos.descuento','productos.nombre as producto')
             ->where('detalle_creditos.idcredito','=',$id)
             ->orderBy('detalle_creditos.id', 'desc')->get();

             return view('creditos.show',['credito' => $credito,'detalles' =>$detalles]);
         }

         public function destroy(Request $request){

             $credito = Credito::findOrFail($request->id_venta);
             $credito->estado = 'Anulado';
             $credito->save();
             return Redirect::to('credito');

        }

         public function pdf(Request $request,$id){

             $credito = Credito::join('clientes','creditos.idcliente','=','clientes.id')
             ->join('users','creditos.idusuario','=','users.id')
             ->join('detalle_creditos','creditos.id','=','detalle_creditos.idcredito')
             ->select('creditos.id','creditos.tipo_identificacion',
             'creditos.num_venta','creditos.created_at','creditos.impuesto',
             'creditos.estado',DB::raw('sum(detalle_creditos.cantidad*precio - detalle_creditos.cantidad*precio*descuento/100) as total'),'clientes.nombre','clientes.tipo_documento','clientes.num_documento',
             'clientes.direccion','clientes.email','clientes.telefono','users.usuario')
             ->where('creditos.id','=',$id)
             ->orderBy('creditos.id', 'desc')
             ->groupBy('creditos.id','creditos.tipo_identificacion',
             'creditos.num_ventas','creditos.created_at','creditos.impuesto',
             'creditos.estado','clientes.nombre','clientes.tipo_documento','clientes.num_documento',
             'clientes.direccion','clientes.email','clientes.telefono','users.usuario')
             ->take(1)->get();

             $detalles = DetalleCredito::join('productos','detalle_creditos.idproducto','=','productos.id')
             ->select('detalle_creditos.cantidad','detalle_creditos.precio','detalle_creditos.descuento',
             'productos.nombre as producto')
             ->where('detalle_creditos.idcredito','=',$id)
             ->orderBy('detalle_creditos.id', 'desc')->get();

             $numventa=Credito::select('num_venta')->where('id',$id)->get();

             $pdf= \PDF::loadView('pdf.credito',['credito'=>$credito,'detalles'=>$detalles]);
             return $pdf->download('credito-'.$numventa[0]->num_venta.'.pdf');
         }


         public function listarMesesPdf(){
            Carbon::setLocale('es');
           $mytime= Carbon::now('America/Mexico_city');
           $meses = [
               0 => '',
               1 => 'January',
               2 => 'February',
               3 => 'March',
               4 => 'April',
               5 => 'May',
               6 => 'June',
               7 => 'July',
               8 => 'August',
               9 => 'September',
               10=> 'October',
               11=> 'November',
               12=> 'December'
           ];

           $fecha = Carbon::parse($mytime);
           $mesIn=  $meses[$fecha->month];
            /*

resources/views/creditos/create.blade.php
@extends('principal')
@section('contenido')


<main class="main">

 <div class="card-body">

 <h2>Agregar Credito</h2>

 <span><strong>(*) Campo obligatorio</strong></span><br/>

 <h3 class="text-center">LLenar el formulario</h3>

    <form action="{{route('credito.store')}}" method="POST">
    {{csrf_field()}}

            <div class="form-group row">

            <div class="col-md-8">

                <label class="form-control-label" for="nombre">Nombre del Cliente</label>

                    <select class="form-control selectpicker" name="id_cliente" id="id_cliente" data-live-search="true" required>

                    <option value="0" disabled>Seleccione</option>

                    @foreach($clientes as $client)

                    <option value="{{$client->id}}">{{$client->nombre}}</option>

                    @endforeach

                    </select>

                </div>
            </div>

            <div class="form-group row">

                <div class="col-md-8">

                        <label class="form-control-label" for="documento">Documento</label>

                        <select class="form-control" name="tipo_identificacion" id="tipo_identificacion" required>

                            <option value="0" disabled>Seleccione</option>
                            <option value="FACTURA">Factura</option>
                            <option value="TICKET">Ticket</option>


                        </select>

                </div>
            </div>


            <div class="form-group row">

                <div class="col-md-8">
                        <label class="form-control-label" for="num_venta">Número Venta</label>

                        <input required type="text" id="num_venta" name="num_venta" class="form-control" placeholder="Ingrese el número venta" pattern="[0-9]{0,15}">
                </div>
            </div>

            <br/><br/>

            <div class="form-group row border">

                 <div class="col-md-8">

                        <label class="form-control-label" for="nombre">Producto</label>

                            <select class="form-control selectpicker" name="id_producto" id="id_producto" data-live-search="true" required>
                            <option value="0" selected>Seleccione</option>
                            @foreach($productos as $prod)

                            <option id="product_selected" value="{{$prod->id}}_{{$prod->precio_venta}}_{{$prod->stock}}">{{$prod->producto}}</option>

                            @endforeach

                            </select><!--- <option value="0" type="number" disabled id="stock" name="stock" class="form-control" placeholder="Ingrese el stock" pattern="[0-9]{0,15}"></label>--->

                </div>

            </div>

            <div class="form-group row">

                <div class="col-md-2">
                        <label class="form-control-label" for="cantidad">Cantidad</label>

                        <input type="number" id="cantidad" name="cantidad" class="form-control" placeholder="Ingrese cantidad" pattern="[0-9]{0,15}">
                </div>

                <div class="col-md-2">
                        <label class="form-control-label" for="stock">Cantidad en stock actual</label>



                        <input value="0" type="number" disabled id="stock" name="stock" class="form-control"  pattern="[0-9]{0,15}">


                </div>

                <div class="col-md-2">
                        <label class="form-control-label" for="stock">Cantidad stock restante</label>



                        <input value="0" type="number" disabled id="stocki" name="stock" class="form-control"  pattern="[0-9]{0,15}">


                </div>

                <div class="col-md-2">
                        <label class="form-control-label" for="precio_venta">Precio Venta</label>

                        <input value="0" type="number" disabled id="precio_venta" name="precio_venta" class="form-control"   >
                </div>

                <div class="col-md-2">
                        <label class="form-control-label" for="impuesto">Descuento</label>

                        <input type="number" id="descuento" name="descuento" class="form-control" placeholder="Ingrese el descuento">
                </div>

                <div class="col-md-4">

                    <button type="button" id="agregar" class="btn btn-primary"><i class="fa fa-plus fa-2x"></i> Agregar detalle</button>
                </div>


            </div>

            <br/><br/>

           <div class="form-group row border">

              <h3>Lista de Ventas a Clientes</h3>

              <div class="table-responsive col-md-12">
                <table id="detalles" class="table table-bordered table-striped table-sm">
                <thead>
                    <tr class="bg-success">
                        <th>Eliminar</th>
                        <th>Producto</th>
                        <th>Precio Venta (MXN$)</th>
                    <th>Descuento</th>
                        <th>Cantidad</th>
                        <th>SubTotal (MXN$)</th>
                    </tr>
                </thead>

                <tfoot>
                   <!--<th>Total</th>
                   <th></th>
                   <th></th>
                   <th></th>
                   <th></th>
                   <th><h4 id="total">MXN$ 0.00</h4><input type="hidden" name="total_venta" id="total_venta">  </th>-->

                    <tr>
                        <th  colspan="5"><p align="right">TOTAL:</p></th>
                        <th><p align="right"><span id="total">MXN$ 0.00</span> </p></th>
                    </tr>

                    <tr>
                        <th colspan="5"><p align="right">TOTAL IMPUESTO (20%):</p></th>
                        <th><p align="right"><span id="total_impuesto">MXN$ 0.00</span></p></th>
                    </tr>

                    <tr>
                        <th  colspan="5"><p align="right">TOTAL PAGAR:</p></th>
                        <th><p align="right"><span align="right" id="total_pagar_html">MXN$ 0.00</span> <input type="hidden" name="total_pagar" id="total_pagar"></p></th>
                    </tr>

                </tfoot>

                <tbody>
                </tbody>


                </table>
              </div>

            </div>

            <div class="modal-footer form-group row" id="guardar">

            <div class="col-md">
               <input type="hidden" name="_token" value="{{csrf_token()}}">

                <button type="submit" class="btn btn-success"><i class="fa fa-save fa-2x"></i> Registrar</button>

            </div>

            </div>

         </form>

    </div><!--fin del div card body-->
  </main>

@push('scripts')
 <script>

  $(document).ready(function(){

     $("#agregar").click(function(){

         agregar();


     });
     $("#id_producto").click(function(){
        mostrarValores();

     });







  });

   var cont=0;
   total=0;
   subtotal=[];
   $("#guardar").hide();
   $("#id_producto").change(mostrarValores);




     function mostrarValores(){

         datosProducto = document.getElementById('id_producto').value.split('_');

         $("#precio_venta").val(datosProducto[1]);
         $("#stock").val(datosProducto[2]);

         $("#stocki").val(datosProducto[2]);



     }

     function agregar(){
        almacen();
         datosProducto = document.getElementById('id_producto').value.split('_');

         id_producto= datosProducto[0];
         producto= $("#id_producto option:selected").text();
         cantidad= $("#cantidad").val();
         descuento= $("#descuento").val();
         precio_venta= $("#precio_venta").val();
         stock= $("#stock").val();
         impuesto=20;

          if(id_producto !="" && cantidad!="" && cantidad>0  && descuento!="" && precio_venta!=""){

                if(parseInt(stock)>=parseInt(cantidad)){

                    /*subtotal[cont]=(cantidad*precio_venta)-descuento;
                    total= total+subtotal[cont];*/

                    subtotal[cont]=(cantidad*precio_venta)-(cantidad*precio_venta*descuento/100);
                    total= total+subtotal[cont];

                   /* var fila= '<tr class="selected" id="fila'+cont+'"><td><button type="button" class="btn btn-danger btn-sm" onclick="eliminar('+cont+');"><i class="fa fa-times fa-2x"></i></button></td> <td><input type="hidden" name="id_producto[]" value="'+id_producto+'">'+producto+'</td> <td><input type="number" name="precio_venta[]" value="'+parseFloat(precio_venta).toFixed(2)+'"> </td> <td><input type="number" name="descuento[]" value="'+parseFloat(descuento).toFixed(2)+'"> </td> <td><input type="number" name="cantidad[]" value="'+cantidad+'"> </td> <td>$'+parseFloat(subtotal[cont]).toFixed(2)+'</td></tr>';*/
                   var fila= '<tr class="selected" id="fila'+cont+'"><td><button type="button" class="btn btn-danger btn-sm" onclick="eliminar('+cont+');"><i class="fa fa-times fa-2x"></i></button></td> <td><input type="hidden" name="id_producto[]" value="'+id_producto+'">'+producto+'</td> <td><input type="number" name="precio_venta[]" value="'+parseFloat(precio_venta).toFixed(2)+'"> </td> <td><input type="number" name="descuento[]" value="'+parseFloat(descuento).toFixed(2)+'"> </td> <td><input type="number" name="cantidad[]" value="'+cantidad+'"> </td> <td>$'+parseFloat(subtotal[cont]).toFixed(2)+'</td></tr>';
                    cont++;
                    limpiar();
                    totales();
                    /*$("#total").html("MXN$ " + total.toFixed(2));
                    $("#total_venta").val(total.toFixed(2));*/
                    evaluar();
                    $('#detalles').append(fila);




                } else{

                    //alert("La cantidad a vender supera el stock");

                    Swal.fire({
                    type: 'error',
                    //title: 'Oops...',
                    text: 'La cantidad a vender supera el stock',

                    })
                }







            }else{

                //alert("Rellene todos los campos del detalle de la venta");

                Swal.fire({
                type: 'error',
                //title: 'Oops...',
                text: 'Rellene todos los campos del detalle de la venta',

                })

            }

     }


     function limpiar(){

        $("#cantidad").val("0");
        $("#descuento").val("0");
       /* $("#precio_venta").val("0.00");*/

     }

     function totales(){

        $("#total").html("MXN$ " + total.toFixed(2));
        //$("#total_venta").val(total.toFixed(2));

        total_impuesto=total*impuesto/100;
        total_pagar=total+total_impuesto;
        $("#total_impuesto").html("MXN$ " + total_impuesto.toFixed(2));
        $("#total_pagar_html").html("MXN$ " + total_pagar.toFixed(2));
        $("#total_pagar").val(total_pagar.toFixed(2));
      }


     function evaluar(){

         if(total>0){

           $("#guardar").show();

         } else{

           $("#guardar").hide();
         }
     }

     function eliminar(index){

        total=total-subtotal[index];
        total_impuesto= total*20/100;
        total_pagar_html = total + total_impuesto;

        $("#total").html("MXN$" + total);
        $("#total_impuesto").html("MXN$" + total_impuesto);
        $("#total_pagar_html").html("MXN$" + total_pagar_html);
        $("#total_pagar").val(total_pagar_html.toFixed(2));

        $("#fila" + index).remove();
        evaluar();
     }



     function almacen(){

        stock = $("#stock").val();
        cant = $("#cantidad").val();
        tot = stock - cant;
        $("#stocki").val(tot);


     }

 </script>
@endpush

@endsection

resources/views/creditos/transfer.blade.php
<form action="{{route('venta.store')}}" method="POST" class="form-horizontal" >
{{csrf_field()}}
<div class="form-group row">
                <label  class="col-md-3 form-control-label" for="id_cliente">Cliente</label>
                <div class="col-md-9">
                    <input value="{{$credito->nombre}}"  type="text"   class="form-control" placeholder="Ingrese el Código" required >

                </div>
    </div>
    <input hidden value="{{$credito->idcliente}}" type="text" for = "id_cliente" id="id_cliente" name="id_cliente"  class="form-control" placeholder="Ingrese el Código" required>




    <div class="form-group row">
                <label class="col-md-3 form-control-label" for="codigo">Documento</label>
                <div class="col-md-9">
                    <input value="{{$credito->tipo_identificacion}}"  type="text" id="tipo_identificacion" name="tipo_identificacion" class="form-control" placeholder="Ingrese el Código" required >

                </div>
    </div>


    <div class="form-group row">
                <label class="col-md-3 form-control-label" for="codigo">Numero de Venta</label>
                <div class="col-md-9">
                    <input value="{{$credito->num_venta}}"  type="text" id="num_venta" name="num_venta" class="form-control" placeholder="Ingrese el Código" required pattern="[0-9]{0,15}">

                </div>
    </div>
    <div class="form-group row">
                <label class="col-md-3 form-control-label" for="codigo">Total a pagar</label>
                <div class="col-md-9">
                    <input value="{{$credito->total+($credito->total*20/100)}}"  type="text" id="total_pagar" name="total_pagar" class="form-control" placeholder="Ingrese el Código" ">

                </div>
    </div>



    <h3>Detalle de Ventas</h3>

<div class="table-responsive col-md-12">
  <table id="detalles" class="table table-bordered table-striped table-sm">
  <thead>
      <tr class="bg-success">


          <th>Producto</th>
          <th>Precio Venta (MXN$)</th>
          <th>Descuento (MXN$)</th>
          <th>Cantidad</th>
          <th>SubTotal (MXN$)</th>
      </tr>
  </thead>

  <tfoot>



     <!--<th><h2>TOTAL</h2></th>
     <th></th>
     <th></th>
     <th></th>
     <th><h4 id="total">{{$credito->total}}</h4></th>-->
     <tr>
          <th  colspan="4"><p align="right">TOTAL:</p></th>
          <th><p align="right">${{number_format($credito->total,2)}}</p></th>
      </tr>

      <tr>
          <th colspan="4"><p align="right">TOTAL IMPUESTO (20%):</p></th>
          <th><p align="right">${{number_format($credito->total*20/100,2)}}</p></th>
      </tr>

      <tr>
          <th  colspan="4"><p align="right">TOTAL PAGAR:</p></th>
          <th><p  align="right">${{number_format($credito->total+($credito->total*20/100),2)}}</p></th>
      </tr>
  </tfoot>

  <tbody>

     @foreach($detalles as $det)
     <input hidden value="{{$det->idproducto}}"   id="id_producto" name="id_producto" >
     <input hidden value="{{$det->producto}}"   id="product_selected" name="product_selected" >
     <input hidden value="{{$det->precio}}"   id="precio_venta" name="precio_venta" >
     <input hidden value="{{$det->descuento}}"   id="descuento" name="descuento" >
     <input hidden value="{{$det->cantidad}}"   id="cantidad" name="cantidad" >
      <tr>
        <td hidden id = "id_producto" name = "id_producto">{{$det->idproducto}}</td>
        <td id = "product_selected" name = "product_selected">{{$det->producto}}</td>
        <td id = "precio_venta" name = "precio_venta">${{$det->precio}}</td>
        <td id = "descuento" name = "descuento">{{$det->descuento}}</td>
        <td id = "cantidad" name = "cantidad">{{$det->cantidad}}</td>
        <td id = "total_pagar" name = "total_pagar">${{number_format($det->cantidad*$det->precio - $det->cantidad*$det->precio*$det->descuento/100,2)}}</td>


      </tr>


     @endforeach

  </tbody>


  </table>


    <div class="modal-footer">
        <button type="button" class="btn btn-danger" data-dismiss="modal"><i class="fa fa-times fa-2x"></i> Cerrar</button>
        <input type="hidden" name="_token" value="{{csrf_token()}}">
        <button type="submit" class="btn btn-success"><i class="fa fa-save fa-2x"></i> Guardar</button>

    </div>
    </form>

@push('scripts')
 <script>

</script>
@endpush